### PR TITLE
Update resource-routing.js

### PR DESCRIPTION
**Pull request by fengzhu**
"update"  does not work because the http_method is set incorrectly. Can you help check it?

### CODE REVIEW

**Comment by Antiokus314** [comment]
Looks like this fix is good (and has been for some time). Other than changes the package.json, is this going to be merged in soon?

**Comment by mshiltonj** [comment]
I understand the correction of the httpd method, but why remove the :format variant? Can we separate the format variant issue form the update of the get/put method?

**Comment by cthulhu** [comment]
Yes, would be nice to get update method fix, since now it doesn't work with default REST-clients.

**Comment by mshiltonj** [comment]
Closing without merging. It's been ... a while ... since I worked on this. It has been mostly rewritten in typescript, and now update works.

**Pull request closed without merging**
